### PR TITLE
Here is the final version of the code. A full calculator.

### PR DESCRIPTION
**Pull request by IanRBr**
This is the full code, with everything in it. If you have any reservations, let me know. Also, I figured out how float works.

### CODE REVIEW

**Comment by IanRBr** [comment]
approve the PR that i created dumbasses

**Review by LilMarz — APPROVED** [review]
"A full calculator" more like Dababy calculator

**Comment by IanRBr** [comment]
uhhhhh so nice

**Comment by Oozegy** [comment]
Good

**Review by Oozegy — APPROVED** [review]

**Review by AosafRahman — APPROVED** [review]
it looks pretty pog

**Comment by IanRBr** [comment]
it feels so good😋☺️😝

**Comment by IanRBr** [comment]
This is me merging and stuff

**Pull request merged**
