### PR TITLE
Ian_branch

### PR DESCRIPTION
**Pull request by IanRBr**
Hey guys I pushed my code that has division, float division (which is like division but with decimals), and the while loop that we need to choose operators and whatnot. Need yall to comment on whether or not my code is good.

### CODE REVIEW

**Comment by LilMarz** [comment]
Ok buddy

**Comment by IanRBr** [comment]
Dude it doesn't say that you approved of the pull request. You have to approve the pull request

**Comment by IanRBr** [comment]
Hey @Oozegy and @AosafRahman yall need to review and then approve my pull request. If u don't like, then comment and tell me what changes I need to do.

**Comment by LilMarz** [comment]
How do I approve

**Pull request merged**
